In [3]:
import pandas as pd

In [41]:
df = pd.read_csv('/Users/kimss/Documents/marong/marong/preprocessed_store_data.csv')
df.head()

,상호명,주소,역 정보,도보 거리,전화번호,운영시간,브레이크타임,메뉴,리뷰,url,...,일,월,화,수,목,평균별점,위도,경도,대표_카테고리,메인_메뉴_형태
0,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,판교역 4번 출구에서 681m,도보 15분,031-724-2566,['매일\xa0 11:00 ~ 21:30'],[],"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",https://place.map.kakao.com/27582913,...,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골
1,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호",판교역 4번 출구에서 809m,도보 17분,02-417-9292,"['매일\xa0 11:00 ~ 21:30', '라스트오더 ~ 21:00']",[],"['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",https://place.map.kakao.com/269932132,...,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이
2,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,판교역 4번 출구에서 848m,도보 19분,031-628-6619,"['10:40 ~ 21:00', '라스트오더 ~ 20:30', '10:40 ~ 21...","['브레이크타임 15:00 ~ 17:00', '브레이크타임 15:00 ~ 17:00...","['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",https://place.map.kakao.com/18561415,...,10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,4.083333,37.402068,127.106671,한식,삼계탕
3,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,판교역 4번 출구에서 924m,도보 20분,브레이크타임 15:00 ~ 17:00,['매일\xa0 11:30 ~ 22:00'],[],"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",https://place.map.kakao.com/409216346,...,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN
4,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,판교역 4번 출구에서 688m,도보 15분,031-724-2929,"['11:30 ~ 22:00', '15:00 ~ 21:30', '11:30 ~ 22...","['브레이크타임 15:00 ~ 17:00', '브레이크타임 15:00 ~ 17:00...","['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",https://place.map.kakao.com/1782830414,...,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,4.153846,37.400694,127.106989,한식,고기구이

In [6]:
df.columns

Index(['상호명', '주소', '역 정보', '도보 거리', '전화번호', '운영시간', '브레이크타임', '메뉴', '리뷰',
       'url', '운영시간_리스트', '금', '토', '일', '월', '화', '수', '목', '평균별점', '위도',
       '경도', '대표_카테고리', '메인_메뉴_형태'],
      dtype='object')

In [42]:
df = df[['상호명', '주소', '메뉴', '리뷰', '일', '월', '화', '수', '목', '금', '토', '평균별점', '위도', '경도', '대표_카테고리', '메인_메뉴_형태', 'url']]
df.head()

,상호명,주소,메뉴,리뷰,일,월,화,수,목,금,토,평균별점,위도,경도,대표_카테고리,메인_메뉴_형태,url
0,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골,https://place.map.kakao.com/27582913
1,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호","['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이,https://place.map.kakao.com/269932132
2,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,"['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,10:40~21:00,10:40~21:00,4.083333,37.402068,127.106671,한식,삼계탕,https://place.map.kakao.com/18561415
3,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN,https://place.map.kakao.com/409216346
4,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,"['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,11:30~22:00,15:00~21:30,4.153846,37.400694,127.106989,한식,고기구이,https://place.map.kakao.com/1782830414

In [14]:
df = df.rename(columns={'일': '일(영업시간)', '월': '월(영업시간)', '화': '화(영업시간)', '수': '수(영업시간)', '목': '목(영업시간)', '금': '금(영업시간)', '토': '토(영업시간)', '대표_카테고리': '대표메뉴', '메인_메뉴_형태': '메인_메뉴'})
df.head()

,상호명,주소,메뉴,리뷰,일(영업시간),월(영업시간),화(영업시간),수(영업시간),목(영업시간),금(영업시간),토(영업시간),평균별점,위도,경도,대표메뉴,메인_메뉴,url
0,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골,https://place.map.kakao.com/27582913
1,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호","['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이,https://place.map.kakao.com/269932132
2,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,"['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,10:40~21:00,10:40~21:00,4.083333,37.402068,127.106671,한식,삼계탕,https://place.map.kakao.com/18561415
3,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN,https://place.map.kakao.com/409216346
4,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,"['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,11:30~22:00,15:00~21:30,4.153846,37.400694,127.106989,한식,고기구이,https://place.map.kakao.com/1782830414

In [43]:
df.reset_index(drop=False, inplace=True)
df.rename(columns={'index': 'ID'}, inplace=True)
df['ID'] = df['ID'] + 1

In [44]:
df.head()

,ID,상호명,주소,메뉴,리뷰,일,월,화,수,목,금,토,평균별점,위도,경도,대표_카테고리,메인_메뉴_형태,url
0,1,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골,https://place.map.kakao.com/27582913
1,2,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호","['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이,https://place.map.kakao.com/269932132
2,3,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,"['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,10:40~21:00,10:40~21:00,4.083333,37.402068,127.106671,한식,삼계탕,https://place.map.kakao.com/18561415
3,4,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN,https://place.map.kakao.com/409216346
4,5,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,"['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,11:30~22:00,15:00~21:30,4.153846,37.400694,127.106989,한식,고기구이,https://place.map.kakao.com/1782830414

In [45]:
df = df.drop_duplicates(subset=['상호명', '주소'], keep='first').reset_index(drop=True)
df

,ID,상호명,주소,메뉴,리뷰,일,월,화,수,목,금,토,평균별점,위도,경도,대표_카테고리,메인_메뉴_형태,url
0,1,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골,https://place.map.kakao.com/27582913
1,2,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호","['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이,https://place.map.kakao.com/269932132
2,3,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,"['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,10:40~21:00,10:40~21:00,4.083333,37.402068,127.106671,한식,삼계탕,https://place.map.kakao.com/18561415
3,4,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN,https://place.map.kakao.com/409216346
4,5,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,"['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,11:30~22:00,15:00~21:30,4.153846,37.400694,127.106989,한식,고기구이,https://place.map.kakao.com/1782830414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,781,메가MGC커피 판교백현화랑초점,경기 성남시 분당구 동판교로 92 백현마을3단지 상가동 1층 104호,"['하츄핑 딸기 밀크쉐이크', '치즈가 펑펑 눈꽃 떡볶이', '빤짝핑 망고 밀크쉐이...","{'리뷰 1': {'별점': 1, '리뷰 내용': '10시 30분까지라고 되어있어서...",08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,1.000000,37.391749,127.118148,카페/디저트,NaN,https://place.map.kakao.com/107494195
693,782,카페만월경 판교백현점,경기 성남시 분당구 판교역로 102 백현마을5단지아파트 나상가동 1층 104호,"['연한아메리카노', '진한아메리카노', '카페라떼', '카페모카', '바닐라라떼'...","{'리뷰 1': {'별점': 3, '리뷰 내용': '음료가 너무 달아요... 혀 마...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,37.390951,127.112714,카페/디저트,NaN,https://place.map.kakao.com/289860524
694,784,커스텀커피 서판교점,경기 성남시 분당구 운중로125번길 6 1층 101호,"['아메리카노', '카페라떼', '바닐라라떼', '아이스티', '청포도에이드']","{'리뷰 1': {'별점': 5, '리뷰 내용': '라떼는 여기만 가요!', '날짜...",08:00~19:00,08:00~19:00,08:00~19:00,08:00~19:00,NaN,10:00~19:00,10:00~19:00,4.333333,37.392302,127.077418,카페/디저트,NaN,https://place.map.kakao.com/554540956
695,785,BK버거 판교점,경기 성남시 분당구 판교역로 136 1층 1036호,"['BK 오리지날버거 세트', 'BK 리얼치즈버거 세트', 'BK 더블리얼치즈버거 ...","{'리뷰 1': {'별점': 4, '리뷰 내용': '더블치즈 먹었는데 맛있네요 ! ...",11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,4.285714,37.392084,127.109167,패스트푸드,햄버거,https://place.map.kakao.com/1737054932
696,786,판교도마집 판교본점,경기 성남시 분당구 판교역로192번길 14-1 1층,"['육즙목살', '꼬들목살', '등심덧살', '쫀득살', '치마살', '된장술밥',...","{'리뷰 1': {'별점': 1, '리뷰 내용': '일하는 여자분 최악입니다\n아 ...",16:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,16:00~24:00,3.222222,37.397511,127.111804,한식,고기구이,https://place.map.kakao.com/362906944

In [46]:
df.reset_index(drop=False, inplace=True)
df.rename(columns={'index': 'ID'}, inplace=True)
df['ID'] = df['ID'] + 1

In [47]:
df

,ID,ID,상호명,주소,메뉴,리뷰,일,월,화,수,목,금,토,평균별점,위도,경도,대표_카테고리,메인_메뉴_형태,url
0,1,2,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골,https://place.map.kakao.com/27582913
1,2,3,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호","['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이,https://place.map.kakao.com/269932132
2,3,4,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,"['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,10:40~21:00,10:40~21:00,4.083333,37.402068,127.106671,한식,삼계탕,https://place.map.kakao.com/18561415
3,4,5,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN,https://place.map.kakao.com/409216346
4,5,6,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,"['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,11:30~22:00,15:00~21:30,4.153846,37.400694,127.106989,한식,고기구이,https://place.map.kakao.com/1782830414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,693,782,메가MGC커피 판교백현화랑초점,경기 성남시 분당구 동판교로 92 백현마을3단지 상가동 1층 104호,"['하츄핑 딸기 밀크쉐이크', '치즈가 펑펑 눈꽃 떡볶이', '빤짝핑 망고 밀크쉐이...","{'리뷰 1': {'별점': 1, '리뷰 내용': '10시 30분까지라고 되어있어서...",08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,1.000000,37.391749,127.118148,카페/디저트,NaN,https://place.map.kakao.com/107494195
693,694,783,카페만월경 판교백현점,경기 성남시 분당구 판교역로 102 백현마을5단지아파트 나상가동 1층 104호,"['연한아메리카노', '진한아메리카노', '카페라떼', '카페모카', '바닐라라떼'...","{'리뷰 1': {'별점': 3, '리뷰 내용': '음료가 너무 달아요... 혀 마...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,37.390951,127.112714,카페/디저트,NaN,https://place.map.kakao.com/289860524
694,695,785,커스텀커피 서판교점,경기 성남시 분당구 운중로125번길 6 1층 101호,"['아메리카노', '카페라떼', '바닐라라떼', '아이스티', '청포도에이드']","{'리뷰 1': {'별점': 5, '리뷰 내용': '라떼는 여기만 가요!', '날짜...",08:00~19:00,08:00~19:00,08:00~19:00,08:00~19:00,NaN,10:00~19:00,10:00~19:00,4.333333,37.392302,127.077418,카페/디저트,NaN,https://place.map.kakao.com/554540956
695,696,786,BK버거 판교점,경기 성남시 분당구 판교역로 136 1층 1036호,"['BK 오리지날버거 세트', 'BK 리얼치즈버거 세트', 'BK 더블리얼치즈버거 ...","{'리뷰 1': {'별점': 4, '리뷰 내용': '더블치즈 먹었는데 맛있네요 ! ...",11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,4.285714,37.392084,127.109167,패스트푸드,햄버거,https://place.map.kakao.com/1737054932
696,697,787,판교도마집 판교본점,경기 성남시 분당구 판교역로192번길 14-1 1층,"['육즙목살', '꼬들목살', '등심덧살', '쫀득살', '치마살', '된장술밥',...","{'리뷰 1': {'별점': 1, '리뷰 내용': '일하는 여자분 최악입니다\n아 ...",16:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,16:00~24:00,3.222222,37.397511,127.111804,한식,고기구이,https://place.map.kakao.com/362906944

In [48]:
df = df.drop(columns=['ID'])

In [49]:
df.reset_index(drop=False, inplace=True)
df.rename(columns={'index': 'ID'}, inplace=True)
df['ID'] = df['ID'] + 1

In [50]:
df

,ID,상호명,주소,메뉴,리뷰,일,월,화,수,목,금,토,평균별점,위도,경도,대표_카테고리,메인_메뉴_형태,url
0,1,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골,https://place.map.kakao.com/27582913
1,2,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호","['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이,https://place.map.kakao.com/269932132
2,3,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,"['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,10:40~21:00,10:40~21:00,4.083333,37.402068,127.106671,한식,삼계탕,https://place.map.kakao.com/18561415
3,4,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN,https://place.map.kakao.com/409216346
4,5,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,"['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,11:30~22:00,15:00~21:30,4.153846,37.400694,127.106989,한식,고기구이,https://place.map.kakao.com/1782830414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,693,메가MGC커피 판교백현화랑초점,경기 성남시 분당구 동판교로 92 백현마을3단지 상가동 1층 104호,"['하츄핑 딸기 밀크쉐이크', '치즈가 펑펑 눈꽃 떡볶이', '빤짝핑 망고 밀크쉐이...","{'리뷰 1': {'별점': 1, '리뷰 내용': '10시 30분까지라고 되어있어서...",08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,1.000000,37.391749,127.118148,카페/디저트,NaN,https://place.map.kakao.com/107494195
693,694,카페만월경 판교백현점,경기 성남시 분당구 판교역로 102 백현마을5단지아파트 나상가동 1층 104호,"['연한아메리카노', '진한아메리카노', '카페라떼', '카페모카', '바닐라라떼'...","{'리뷰 1': {'별점': 3, '리뷰 내용': '음료가 너무 달아요... 혀 마...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,37.390951,127.112714,카페/디저트,NaN,https://place.map.kakao.com/289860524
694,695,커스텀커피 서판교점,경기 성남시 분당구 운중로125번길 6 1층 101호,"['아메리카노', '카페라떼', '바닐라라떼', '아이스티', '청포도에이드']","{'리뷰 1': {'별점': 5, '리뷰 내용': '라떼는 여기만 가요!', '날짜...",08:00~19:00,08:00~19:00,08:00~19:00,08:00~19:00,NaN,10:00~19:00,10:00~19:00,4.333333,37.392302,127.077418,카페/디저트,NaN,https://place.map.kakao.com/554540956
695,696,BK버거 판교점,경기 성남시 분당구 판교역로 136 1층 1036호,"['BK 오리지날버거 세트', 'BK 리얼치즈버거 세트', 'BK 더블리얼치즈버거 ...","{'리뷰 1': {'별점': 4, '리뷰 내용': '더블치즈 먹었는데 맛있네요 ! ...",11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,4.285714,37.392084,127.109167,패스트푸드,햄버거,https://place.map.kakao.com/1737054932
696,697,판교도마집 판교본점,경기 성남시 분당구 판교역로192번길 14-1 1층,"['육즙목살', '꼬들목살', '등심덧살', '쫀득살', '치마살', '된장술밥',...","{'리뷰 1': {'별점': 1, '리뷰 내용': '일하는 여자분 최악입니다\n아 ...",16:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,16:00~24:00,3.222222,37.397511,127.111804,한식,고기구이,https://place.map.kakao.com/362906944

In [25]:
df.to_csv('판교_식당_카페.csv', index=False)

In [58]:
import ast
import numpy as np
import re
import emoji
from sentence_transformers import SentenceTransformer

# 모델 로드
model = SentenceTransformer('snunlp/KR-SBERT-V40K-klueNLI-augSTS')

# 불용어 리스트
stopwords = set(['것', '정말', '좀', '너무', '매우', '입니다', '하는', '하고'])

# 단어 반복 줄이기
def reduce_repeated_words(text):
    return re.sub(r'(\b\w+)\1{1,}', r'\1', text)

# 한국어 텍스트 클린 함수
def clean_korean_text(text):
    if not text:
        return ''
    text = emoji.replace_emoji(text, replace='')
    text = re.sub(r'[^가-힣\s]', '', text)
    text = reduce_repeated_words(text)
    words = text.split()
    words = [word for word in words if word not in stopwords]
    return ' '.join(words)

# 리뷰 평균 임베딩 함수
def embed_reviews_avg(review_str):
    try:
        review_dict = ast.literal_eval(review_str)
    except:
        return None

    review_texts = []
    for review_info in review_dict.values():
        content = review_info.get('리뷰 내용', '')
        if content and content != '리뷰 없음':
            cleaned_content = clean_korean_text(content.strip())  # ✅ 여기 추가
            if cleaned_content:  # 전처리 후에도 내용이 남아있을 때만
                print(cleaned_content)
                review_texts.append(cleaned_content)

    if not review_texts:
        return None

    embeddings = []
    for text in review_texts:
        prompt = f"이 리뷰가 묘사하는 분위기를 임베딩하세요: {text}"
        emb = model.encode(prompt)
        embeddings.append(emb)

    avg_embedding = np.mean(embeddings, axis=0)
    return avg_embedding.tolist()  # ✅ 리스트로 변환해서 저장

# 적용
df['리뷰_평균임베딩'] = df['리뷰'].apply(embed_reviews_avg)

평냉 초보로서 입문용으로 적극 추천 가능한 짙은 육수의 맛 두번때 방문 역시 맛있다
어복쟁반은 진짜임 만두도 지나치게 달지 않고 좋아하는 맛임 평냉은 순혈 평냉파 입장에서 조금 아쉬울 수 있음
점심시간임에도 자리는 잘 빠지는 점은 좋음 하지만 국물이 생각보다 꽤 많이 짬
평냉 매니아로서 냉면은 맛이 없네요
평양냉면 땡길때 가기 좋은곳 엄청 특별하진 않은데 깔끔해요
방문 어복쟁반에 소주 한잔 최고의 조합이라 말할 수 있음
냉면과 불고기 맛이 밍함 어복쟁반은 기가 막힘 평점은 어복쟁반 기준임
만두맛집
주말이라 조용한 가운데 눈치보지않게 찬도 넉히 주시고 편안하고 맛있는 식사 잘먹고 맛있게 먹었어요
다른 지점에 비해 형편없음 만두국 육수도 맛없고 비빔냉면도 맛없고
아쉬워요
아쉬워요
세상에나 요즘 식당에 바퀴벌레가 나오다니 기겁하고 도망나왔네 불친절의 왕 지나가다 간판도 보기싫음
냉면 맛은 그럭저럭 양은 조금 부족함 가격이 전체적으로 비쌈
와 칠천오백원짜리 녹두전 하나 시켰는데 진심 손바닥보다 작게 나오는데 심지어 두껍지도 않음 다른데선 한끼 식사값인데 이런 배짱장사는 첨보고 냉면양도 줄음 코로나사태 거치면서 전반적으로 양 줄인게 진짜 양심 없어진 수준이네요 마진 더보기
온반 만두국 녹두전 접시만두 냉면 다 맛있어요
어복쟁반 먹어봄
만두상함
만두전골 맛있으요 담백하면서 살짝 칼 더보기
만두전골이랑 평양냉면 맛이쏘요
왜 이렇게 평이 낮지 제 입맛이 이상한굴까요 저는 너무너무 맛있었어요 담백하면서도 칼한 어복쟁반 국물도 진짜 좋고 고기랑 야채랑 같이 먹으니 눔 좋네요 평양냉면은 다른데보다 덜 짠거 같아서 좋았고 비빔냉면은 쏘였어요
어복쟁반은 먹을만 한데 다른건 별로 특히 이북음식임에도 불구라고 만두국이 엄청 짜다
평범한 내 입맛에는 괜춘했음
비빔이 더 맛있어요
평냉치곤 간이 있는 편 전반적으로 만두 빈대떡 등 다 괜찮았음
냉면은 소
가격이 주변보다 천 더 비싸네요 맛은 은반 먹었는데 무난했어요 냉면은 다들 별로라고
간이 있는 편이지만 기본적으로 맛있다
처음 먹어본 평양냉면 나름 먹을만 하긴 했는데 그렇게 맛있는지는 모르겠다 그리고 가격이 비싸다
평가혹 맛가혹
초딩 입맛인 나에겐 먼 평양 이 집은 김치가 맛있네
냉면 원 비림
평양냉면 맛으로는 하위권 별점 기준 재방문 의사 없음 찾아서 더보기
정자동 본점에서 먹던 맛과 똑같은 평양냉면의 맛 오픈 초기이지만 사람들 많아 분 넘게 기다려야 먹을 수 있음
비싸깅한데 맛은 있어요
오랜만에 먹는 봉피양 육수는 여전히 끝내줬고 면이 뭔가 살짝 딱한 느낌 첫입 먹자마자 조금 당황했지만 더보기
양곰탕 맛있어요 기름지지만 특성이겠죠
고깃집 많이 다녀봤지만 이곳은 특히 아쉬웠네요 일단 서버분 고기 굽는 스킬이 부족해요 육즙 다 빠져서 인분 원 돈값 못하는 고기였어요 한우를 조금씩 구워서 먹는 게 아니라 한꺼번에 돼지고기 굽듯이 하 더보기
봉피양 평냉은 말이 필요없죠 친구들이랑 맛있게 먹었어요 저녁시간엔 주차 무료인것도 아주 편리하네요
퀼리티가 좋습니다 별도 비용없이 룸에서 식사도 가능해서 모임하기 좋아요 돼지갈비가 다른 식당과 비교불가 물로 더보기
평냉먹고싶어 방문했어요 가격은 있지만 봉피양이라는 이름을 믿고 갈수 있는곳
가격 대비 글쎄요
아무리 한우라고해도 배달이라고해도 한우곰탕 원 심한거 아닙니까 양도 부실 후추 소금도 없고
뒤에서 직장인 회식으로 간 거랑 가족들이랑 간 거랑 온도차 무엇 밑에 물 더보기
그리운 봉피양 평양냉면
메뉴 주문 하려는데 아주머니들 계속 쌩깜 그래도 만두는 맛있었다
냉면이랑 양곰탕 먹을만 해요 고긴 내돈으로 못 먹죠
평냉 진짜 대박
예전에 직원들이랑 같이 냉명을 먹으러 퇴근 이후에 갔더니 테이블이 만석이였는데 사장님으로 보이는 분이 그냥 식사만 하실꺼면 다른곳으로 가시라고 문전박대를 당했던 그 가게 그래서 그 이후로 다른 지점 다님
가격에 비해 별로임
판교에서 점심 식사했는데 뭐 가격표 보시면 아실 듯 가격에 비해 시설은 별로고 음식은 맛은 괜찮은데 가성비가 떨어져요
평양냉면 초보자로 가장 좋아하는 집 담백한 육수 생채 만두까지 조합도 좋으나 다소 비싸다
맛은 늘 기본 이상 근데 방문할 때마다 맛의 편차가 있습니다 특히 탕 종류에서요
을밀대나 동무식당보다는 저 좋은 느낌
평양냉면 먹으러 방문한 곳 육수가 자극적인 맛 정인면옥보단 간이 조금 있는 맛입니다
양곰탕은 이름 바꾸셔야 할 듯 곱창 내지 다른 부위가 대부분이고 정작 양은 새끼손가락 한 마디 만큼 들어있음 이상해서 직원에게 더보기
명성에 기대는 집 직원분들은 힘들어보이시지만 친절하게 대해주시네요 고맙습니다
둘이 가서 점심지나서 간단히 요기나 하려고 냉면하나에 사리 시켰는데 사리추가는 나눠 먹으면 안된다고 혼자 먹으라고함 신박한 더보기
음식은 괜찮았는데 공기가 안좋아요 머리가 아플정도로 연기가 쌓여요
브레이크타임 없어서 좋음
음식은 괜찮은데 식사 주문을 했는데 다른 음식이 나와서 이야기를 했더니 그냥 드시라고 하네요 당황스러웠습니다 다른 직원분이 와서 처음 주문한 음식으로 다시 주기는 했습니다
두번 안가고 싶네요직원분들 불친절하 더보기
예약 시스템에 등록 해봐야 호구됨 나중에 들어온 사람 먼저 자리내주고 먀냥 기다릴 뻔 뭐하러 만들어 놓은건지
토요일 점심시간 방문 손님은 띄엄 앉을 수 있을 정도 적당히 한산했음 친절하신 이모님이 잘 챙겨주셔서 만족스 더보기
맛있네요점 정도 됩니다
솔직히 진짜 비쌈 비싸도 비쌈 근데 고기는 진짜 맛있음
별점 개 줍니다 카오놈들오면 맛없게 해주세요
냉면 말고 고기 먹으러 가는곳
갈비탕 만천원 잘못 쓴거 아닙니다 진짜 만천원 만천원이었는데 더보기
이곳은 소고기보다 돼지갈비가 진리시다
고기육수 강한 평양냉면 점심 세트로 나오는 수육이 맛있네여 고기가 비싸긴 하지만 맛있어요
이거 뭐 배짱 장사가 따로 없네요 평일 점심시간에는 일찍 가도 자리가 없다고 하면서 예약하라고 해서 전화로 예약하려고 하니 인은 예약 받지도 않네요 단체만 받 더보기
육회다 육회 육회가 맛있어영 제 입맛엔 소양념갈비소갈비 고기는 진짜 질이 좋다는게 바로 느껴지네요
돼지갈비 맛있으나 가격대비는
맛은 좋은데 가격이 비싸요
맛있피양
고기도 다 구워주시고 짱맛있었어요 저염김치가 진짜 맛있어요
돼지갈비 원 고기먹고 나오는 넹면이 원 가격이 장난이 아님 가성비 낮고 특별한 맛은 없음
양곰탕
고기가 엄청 비싼데 먹어보면 또 그 값어치를 하는게 신기함 갈빗살이 입 안에서 살 녹는다 평양냉면은 보급형 맛이라 원조가 입에 맞지 않던 사람도 입문하기 수월하다 근데 여하간 여기 음식은 비싼게 문제
가격이 워낙 비싸서 평양냉면 괜찮지만 능라도가 심하게 더 땡긴다
배불러서 맛이 기억이 안 나요 다시 가봐야겠어요
다른 가게의 갈비탕과는 달라요 엄마가 해준 소고기무국이랑 맛이 비슷합니다 계속 떠 더보기
일단 가격이 비싸요 양곰탕 먹었는데 순두부찌개 국물에 양곱창 등이 들어있는 같아요 나중에 돼지갈비를 먹어보고 다시 평가할게요
설렁탕은 중상은 듯 다음번에는 고기를 도전
상황삼계탕 들깨삼계탕 둘 다 맛있음 걸쭉한 국물에 고기는 살 녹음 자극적이지 않고 담백함 깍두기도 좋은데 개인적으로 열무가 더 좋았음
예약하고 가면 빨리나옵니당 맛있게 먹었습니다
엄마랑 완전 자주 가는 삼계탕집 시 이후에도 갈 수 있고 맛도 깔끔하고 반찬도 열무 깍두 고추지 양파로 다양해서 좋음
맛집
복날에 한 번 정도 엄청 시끌벅적해요
회식장소로 좋아요
주인 아주머니 불친절
맛 좋고 든한 삼계탕 어르신들 많음 한약재 냄새는 세서 이런 냄새 못맡는 일행 있다면 주의
복날 되믄 자주 찾게 되는 곳
맛있고 서비스도 좋아요후기보니 복불복인듯 여튼 건물주차 편하고 무난히 맛있습니다
맛있어요 근데 친절하진 않아요
훌륭한 맛의 삼계탕집 깔끔한 꾸덕한 국물 맛있어요 엄지척
삼계탕은 여기가 최고임 상황삼계탕 강추 서현 고려삼계탕보다 맛있음
들깨를 시켰는데 들깨맛이 안 남 한마리를 먹었는데 배고픔 그래도 맛있음
들깨삼계탕 먹을만하나 호수삼계탕을 생각하고 먹는다면 실망할것이다 서버분께 확인한 내용 한방삼계탕 한방 더보기
먹어본 삼계탕중 젤 맛있음 삼계탕 먹고 싶을때마다 가는곳
포장해서 먹었는데도 깔끔하고 맛있네요
삼계탕 국물 맛있음
인테리어 같은거 전혀 없는 식당인데 음식은 꽤나 맛있다 인용 닭볶음탕뚝딱이 먹고싶을땐 이곳으로
존맛탱
백숙이 맛있어서 자주 다님 호기심에 뚝닭이랑 닭볶음탕 먹었는데 대박 얼큰힌게 땡길때 시키면 좋을 듯
기본 삼계탕 원 닭고기가 무지 야들하고 맛있어요 국물은 끈적한 편이라 탕을 생각하시면 안되고 죽을 생각하시면 될 같습니당
복날에 미어터짐 가끔 가는 집인데 괜찮다
여기 볶음밥집인가요 왜 대표 사진이 볶음밥
무난 삼계탕
판교네서 삼계탕 가성비 좋은곳
판교에 여기보다 나은 삼계탕집이 분명 있을터인디
내 사랑 라즈지 최고 맛집 라즈지 여기만큼 잘 곳이 없음 닭 질은 물론이고 고추는 과자처럼 튀겨져서 남김 없이 다 먹게 되는 곳
몇 번 갔는데 추천하고 싶은 곳이에요 인 만원 정도 생각하심 될 같은데 분위기 맛 친절함 다 좋아용 부모님이랑 같이 갔는데 친절하셔서 갬동
넘 맛나게 잘먹었어요 직원분들도 굉장히 친절하시고 크림새우가 남아서 포장 부탁드렸는데 새로운 요리처럼 다시 예쁘게 데코까지 해주셔서 큰감동을 받았습니다 콜키지도 무료 한병 가능하구요 이모든걸 따지 더보기
제가 찾아서 지인들 데리고 방문했는데 일단 주차가 편한게 좋았구 직원분들도 엄청 친절하구 전부 다 룸이라 좋았습니당 음식은 저나 지인들 전부다 맛있다고할정도로 좋았구 메뉴판 봤을땐 가격이 비싼가 싶었는데 메 더보기
여기가 가격대비 영이라고 가성비가 좋습니다 이정도 퀄리티에 양이라니 맛있게 잘먹었습니다
가격대비 영
요즘 흑백요리사로 핫한 동파육이 핫 해서 여기서 먹어봤는데 맛있음 양장피 그것도 괜춘 백짬뽕 가격 더보기
맛있었습니다 재방문후 다른메뉴 먹어보고 맛나면 점수 더 올리겠습니다
양장피 고급 중식당보다 반단계 업그레이드된 맛 전가복 이집만의 독특한 맛 동파육 동파육 별로인 내가 끝까지 소스발라먹게 만드는 맛 짜장면 배가 부른데도 이걸로 술 한병 더 시키게되는 맛 다음에 다른요리들을 기대하게되는 집
가격이 안아까운 정성스런 맛과 양
판교 팔복 고급스러운 중식당 서비스도 좋고 친절합니다 룸으로 되어 더보기
고기가 맛있고 질도 좋아요 직원분들이 다 구워주셔서 편하고 친절해서 넘 좋았습니다 특히 된장술밥 짱 또 갈게욥
주말에 가도 주차하기 편하고 고기 맛있게 직접 구워주시니 가족행사로 외식 있을때마다 화포식당으로 갑니다
개존맛 가게도 깔끔하고 친절함 고기 퀄이 남다름 또올듯
고기 질이 일단 엄청 좋습니다 직원분들이 잘 구워주셔서 먹기 편했습니다 매장도 청결하고 고기도 맛있고 사이드메뉴도 엄청 맛있었습니다
맛있어요 판교 등 고깃집
친구랑 먹고 맛있어서 가족들도 데리고 갔는데 다 극찬을 했던 고기도 맛있게 구워주심 판교에서 젤 자주 가는 고기집 됐어요
주차도 편리하고 직원들이 고기를 직접 구워주셔서 편안하게 이야기하며 만족스러운 식사를 나왔습니다 음식도 맛있게 잘 먹었습니다
먹지도 않은 음식을 결제하라뇨 특히 회식할 때 조심하세요
직접 구워주고 넘 맛나요 판교 삼겹살 맛집
매장 분위기는 정신없고 시끄러운 편 직원들 또한 그렇게 친절하진 않고 그치만 고기들은 다 맛있음
맛은 있음
삼겹살 맛집 친절 회식은 화포식당
저녁시간에 두명이면 자리차지한다고 입장 못하게 한다 적당히 맛있긴 했었는데 싸가지없어서 두번다신 안갈듯
일단 고기가 맛있고 먹어본 고기 중에 손꼽힙니다 직원분들도 다들 친절하시고 고기 신경써서 잘 구워주셔서 만족스러웠습니다 추가한 고기가 살짝 탔는데 괜찮다고 했는데도 바꿔주셔서 감사했습니다 판교 올 일 있으면 꼭 또 갈 같아요
최악 위생이 개판입니다 구워주는 고기는 계속 떨어뜨리고 불조절하는 심지어 스위치에도 떨어뜨리더니 그냥 불판으로 주문지가 음식 위에 올라가있고 진짜 최악입니다
시끄러운 빼고는 좋아요 직원분들도 대응 빠르고 고기도 진짜 맛있어요
오늘 회식이라 자리 없대요
고기는 맛있는데 에어컨이 켜졌는지 안켜졌는지도 모르는 신기한 업장 직원도 덥다고 고생 손님들도 덥다고 고생 온도 내려달라니까 에어컨 꺼져있었음 왜 사서 고생하는지 아무도 모르는 미스테리
불친절함 불러도 안오심 고기를 상당히 못구우심 테이블 간격좁고 작음 태우기 일보직전 아마 초보신듯 내가 더보기
판교에서 퇴근할 때 돼지고기 생각나면 무조건 오는 곳
회식장소로 좋긴한데 손님이 많아요 고기 진짜 맛있네요
회식장소로 최고예요
맛있어요 회식자리로 안성맞춤
비계가 많아서 깜놀 회사 사람들이랑 단체로 갈때와 주말에 아이들 데리고 갈때와 고기 상태가 달라 놀람 직원은 친절함
이 집 선결제 안됩니다 참고하세요
오겹살 맛겹살
고기가 맛있음 재방문 싶음
전체적으로 괜찮습니다 목살과 살짝 시끄러운 부분은 아쉬웠네요
고기도 직접구워주시는게 짱이였어요 항상 제가 고기를 구웠었는데 구워주셔서 편히 먹고왔어요 맛도 맛잇고 직원분들도 친절하셨습니다
고기도 직접 구워주시고 맛도 괜찮아요 저희 팀은 인원이 있어서 안쪽 방으로 안내해주셨는데 사람많은 불금에 조용히 식사 잘 갔습니다
고기 직접 구워주시는게 제일 좋았습니다 맛있게 잘 먹었어요 다음에 꼭 다시 방문하겠습니다
국 산 사 케 대 방 어
자주 이용하는 고기집인데 예약하고 가면 웨이팅 없이도 먹을 수 있어서 참 좋더라구요 직원분들이 고기도 다 구워주셔서 고기를 잘 못굽는 저에게는 안성맞춤이랍니다 김치가 진짜 맛있어요
친절하고 맛나요
아기 태운 유모차 가지고 갔다가 쫓겨남 공간 충분함에도 불구 한 직원은 타일때문에 유모차 반입이 안된다는 말같지도 않은 말과 귀찮은 태도로 안된다고 했고 사장또는 매니저라고 사람은 되려 내게 어떻게 하냐고 물음 보통은 의자를 옮 더보기
아주 만족
넘 맛있었음 아이스크림 기계는 언제 고쳐지나용
환기가 잘 안 되는 것빼곤 다 만족해요 육회도 맛있어요
장어도 진짜 크고 맛있어요 조용해서 지인과 식사하기에 적합했습니다
예약하고 갔는데 맛있게 잘먹었어요 번창하세요
판교 회식장소 탑티어 인곳입니다 장어를 안좋아하던 동료들도 여기 갔다오고선 잘 먹어요 소고기도 세트로 파는데 질이 좋아서 소고기집 안가도 충분히 맛있게 먹었습니다 육회도 양도 많고 실하고 더보기
음식을 한시간 가까이 기다렸는데 주문도 제대로 안 들어갔습니다 테이블 관리가 하나도 안 됩니다
무난합니다
무난합니다 구워줘서 편하네요
여기 가족들이랑 자주오는곳 칭구랑도왔던곳 맛있고 맛있고 맛있는곳
장어가 튼실하고 소고기도 맛있어요 가성비굿
소규모 회식때 자주 방문함 많이 먹게 됨
점심에 지나가다가 불난 줄 지나가는 사람들과 빌딩에 엄청 민폐 중
맛있습니다
맛있네요 점심 키로 만
회식으로 굿
회식의 디폴트
근처 갈만한 장어집이 몇개 없어서 그런대로
점심세트를 먹었다 먹으면서 또 오고 싶어졌다 그러나 번째 방문 후 별을 하나 지워본다 더보기
장어 굿
괜찮음
장어 맛 갠춘
카이센동 먹었습니다 맛있긴 한데 재료가 약간 부실하다는 느낌이 들었어요 그래도 직원분들도 친절하시고 혼밥하기도 좋아보여서 종 갈 같아요
맛있습니다 양은 조금 적게 느껴집니다 점심시간에 주변 회사사람들에게 인기만점
여긴 뭐 다맛있네요 점심 또는 퇴근후 맛있는한끼로 딱인듯
카이센동 회 상태는 괜찮았고 문어 참치 새우장은 살짝 아쉬웠습니다 더블인데도 양은 모자랐습니다
덮밥 전반적으로 맛있어요 평일 점심시간엔 웨이팅 있습니다
스테이크동 맛있어요 소고기 부위 같은 건 잘 모르는데 오늘 토시살이 맛있다는 건 확실히 기억해두었어요 카라이 규동도 생각보다 맵긴 한데 맛나요 카레 부타동이랑 더보기
얼마전 방문시 음식은 괜찮았는데 알바생이 불친절 마감 시간까지 시간은 남았었던 같은데 나가라는 듯 마주보는 자리에서 인상 쓰며 째려보고 한숨 쉬 더보기
보통
이 음식을 만들었다 고 말할 수 있을까 고기도 까맣게 타고 브로콜리는 아예 타서 뭉개졌다 맛있다고 들어서 이노밸리에서 찾아간건데 다신 갈 일 없다
맛을 논하기 전에 튀김 음식들의 튀김상태가 별로임 일식에서 이런 튀김이라니 용서가 안됨
항아리밥 왜 항아리에 넣었을까 특색을 잘 모르겠음 간장새우는 딱 하나 문어도 생문어아니고 말린문어를 사서 조린거같음 연어토막 조금 그냥기냥긔녕 먹음
스테이크 덮밥 맛있네요
원래 일식을 좋아함 근데 여긴 또 맛있음 가격만 착하다면
굿
음식은 맛있어요 점심시간에 사람이 몰리면 음식 나오는게 뒤죽박죽이 되는거 같아요 기다림
일단 입장 직후 테이블 청결 상태가 좋지 않아서 감점 서빙하시는 분 표정이 좋지 않아서 주문하는 나도 죄송스러웠음 음식 맛은 나쁘지 않은데 양이 적어서 별점을 많이 줄 수가 없다
해물 짬뽕 비슷한 맛이었는데 자극적으로 맵고 짜지 않아 맛있음
예약해도 웨이팅있는건 그렇다해도 카페로 안내해준다면서 막상 그런거없고 오래 지체되면 음료 준다해놓고선 말하기전까지 모른 더보기
울프스덴 리뉴얼이 드디어 끝이나 예약하고 방문했습니다 결론부터 말하면 음식은 맛있었지만 친절이나 분위기는 조금 아쉬웠습니다 리뉴얼 끝나길 기다린 분이 많았던 탓인지 더보기
맛있어요 아주 좋아요 가격은 있지만 전체적으로 요리가 좋습닉다
맛있고 좋아요 파스타랑 스테이크가 굿
분위기 맛 다 괜찮았는데 접근성 가성비 안좋았음
판교에서 양식 제일 맛있어요
직원 회식으로 맛있게 먹었습니다 스테이크 고기 퀄리티 좋더라고요 스파게티는 양이 많지는 않습니다 나눠 드시려면 여러게 시키셔야 더보기
파스타 리조또 맛 괜찮았습니다 가격대비 양 그저 그렇습니다 스테이크 양 표기 더보기
아썸아이디어 라고 영수증에 써 있네요 상호명이랑 다름 생면파스 더보기
내 돈내고는 못올 많이 비싼데 돈값 못하는 집 나는 막입이라 맛나게 먹었으나내돈이었으면 피눈물 흘릴정도로 비쌈 같이온 동료분들은 유럽 여 더보기
판교에서 가장 좋아하는 음식점입니다 모임이 있을때 꼭 이곳을 우선적으로 확인합니다
언제 가도 괜찮은 정통 이탈리안 식당입니다
통로에 세팅된 테이블간 간격이 좁아서 옆 테이블과 함께 식사하는 듯 함 통로쪽 앉는 사람은 서 더보기
가격대비 음식 퀄리티가 떨어져요
맛있는지 잘모르겠음
라구뇨끼 굿 트러플 스테이크 굿 근데 가게가 살짝 좁아서 별 하나 뺐습니다
맛도 없고 불친절해서 기분 좋게 갔다가 기분 나쁘게 나오는곳
스파게티아에서 알바하다 나온 사람이 주방보는듯요 서빙은 브레이크타임 거의 다 됐다고 떽거리고 만원어치 쓰고 기분만 나빴습니다
가성비 안 좋고 분위기는 삼겹살 식당 정도로 생각하고 오시면 될 같아요 음식 솜씨가 뛰어나지는 않으나 판교 회사원이라면 위치가 좋아 한번쯤 갈만한 곳
봉골레는 괜찮았고 주문 잘못된 마레 파스타는 달고 피클과 올리브도 달고 가격대비
쏘
웨이팅 해가면서 먹을 맛은 아닙니다 오래 방문한 집인데 초심을 잃은건지 발전을 안한건지
엔초비오일 원툴
버섯샐러드 양도 많고 맛잇어요 날 좋은날에 방문하면 바람도 선하니 불고 기분좋게 드실 수 있습니다
파스타도 괜춘한데 스테이크 최고
음식 괜찮았어요 공간이 좁은 부분이 아쉽네요
카페가 생각보다 좁고 테이블간의 간격이 좁아서 조금은 소란스러운거 감안하셔야해요 명란뇨끼는 아주 맛있어요
자리가 붙어있어요 짜고 음식맛도 별로였어요
여기 가성비 됨 판교에서 이 가격에 이 퀄리티 서비스 해주는곳 드뭄 여러번 방문했었는 더보기
뇨끼생기면서 가봄 들어가자마자 환기안되는지 연기가 자욱해서 들어가기 싫었어요 매장이 깔끔한 느낌은 없었고 솔직히 특출나게 맛있는 느낌은 없었어요
마르게리따 피자가 넘모 맛있었어요 그리고 샐러드에 뿌려주는 올리브오일 맛있다
맛있어요
일단 별 한개도 아깝네요 경과요약 예약하고 방문 입구에서 응대를 기다리니 사장인지 매니저인지 남자가주말카운터로 오라고 함 자 더보기
스텔라 맛있네요 오일 파스타도 맛있었어요
오예 라무진을 가려했으나 문이 닫은 바람에 앞에 있는 울프스덴에서 양고기와 파스타를 먹었어요 더보기
트러플 오리지널 까르보나라
돈아까워요 특히 피자 개노맛
스테이크 리조또 파스타 개 시켰는데요 맛 없기가 힘든 스테이크가 제일 별로 안 더보기
가격대비 퀄이그렇게 훌륭한진모르겠고 양도적어요 그리고 리조또는 버섯향이 너무강하고 살짝 맹맛느낌이라 호불호가 갈릴것같네요
요즘 파스타가 만원 넘는 추세라 이가격에 이정도 퀄이면 훌륭합니다 특히 트러플가격이 괜츈하고 갠적으로 양갈비 넘 맛나요 분위기 괜찮고 직원분들도 친절하세요 와인가격 착하고 콜키지 프리라 사실 거의 와인마시러갑니다 이래저래 자주 찾게 되네요
무난
처음에 먹었을 땐 게살 들어간 리조또가 넘나 맛있었는데 이번엔 게의 맛이 잘 안나고 그냥 크림리조또 같았어요 피자도 무난하고 스테이크는 익힘도 적당하고 먹을만해요 총평은 그냥 나뿌지안타하
맛잇어용 고기도먹고싶다
맛있어욤
음식의 재료에 소스를 겉에만 살짝 발라먹는 느낌이랄까 재료 안에 소스의 맛이 전혀 배어있지 않다 풍미를 더 많이 낼 수 있는 조리법으로 개선해야 할 듯
아니 도대체 이 좋은 곳이 평점이 왜 이런가요 서비스 맛 그리고 고객마인드 뭐 하나 빠지는게 없습니다 최애 레스토랑 울프스덴 흥하세요
서비스도 괜찮고 맛도 있어요
그냥 그냥 특별하진 않음
그럭저럭 가격대비 좋은 편은 아니지만 주변에 이탈리안이 몇개 없어서 가끔
맛있고 비싸고 양작고
스테이크 부드러워서 목넘김이 좋타 내가 좋아하는 봉골레 깔끔한 레시피로 만든듯 오늘의 기대메뉴 꽃게 리조또 더보기
넘 비싸고 맛있는지 모르겠어요
와인 친화적인 비스트로 맛도 중상위권이다
판교에서 제일 자주 가는 양식집이에요 점심 회식 하기에도 좋고 예약도 가능하고 특히 친절한 서비스가 더보기
직원들 맨날 길거리 나와서 담배피는 개념없는집 판교 직장인들에게 이런 민폐가 없음 구석가서 펴라 너네때문에 회사사람들도 절대 여기 안가려함
맛은 괜찮았는데 가격이 비싸서 점 뺐어요 점심부터 예약손님 엄청 붐비더라구요 예약 필수인듯 합니다
근처 회사 다닐 때 자주 갔던 곳인데 인테리어 리모델링 이후 분위기가 별로입니다 이전에는 가격대가 있어도 분위기가 좋아 약속장소로 괜찮았는데 이제는 아닙니다
우니파스타는 비려요 분위기는 좋아요
점도 아까움 판교 테크노벨리 직장인 상대로 장사해서 맛없어도 비싸게 잘 팔림 테이블 간 간격은 좁고 점심엔 시장수준으로 시끄러움 먹고 있는데 그릇 치우려고 하지 않나 물어보지도 않고 많이 부족한 서비스
점심회식으로 왔고 피자는 미리 사전에 주문해야 그외는 무난했던 같아요 봉골레 드신 분은 해감이 전혀 안되서 모래를 자주 씹었다는 평이 있었고 우대갈비랑 뇨끼 드신 분들은 맛있었다네요
실외 온도 도 습도 인데 야외로 안내해주려고 해서 기겁했어요
맛 가성비 모두 최고 안내해주시는 분도 친절하시고 특히 뇨끼가 굉장히 맛있어요 예약해야한다는 번거로움이 있지만 충분히 감수할만한 맛집이라고 생각합니다
맛있었어요 와인도 저렴해서 좋아요
예약필수 진짜맛집 뇨끼가 대박 남자친구랑도 오고 회식하러도 오는 곳입니다 가격이 있지만 맛있어요 팀장님 상무님도 인정했음
재방문은안해요
아 리뷰 보고 갈걸 가격대비 별로입니다 사람 많아서 갓더니 층은 덥고 일단 에어컨 잘 안 더보기
웬만해선 댓글 안 쓰는데 이건 아닌 거 같아서 댓글 남깁니다 시가 안 돼서 방문했고 주문한 지 얼마 안 돼서 주방 마감이라고 라스트 오더를 받더군요 시 분 영업 종료로 알고 갔는데 물어보니 시에 종료라고 들었습니다 홀에 오픈 된 더보기
층 테이블 간격도 좁고 맛도 아쉬웠어요 뭔가 직원분들 서비스도 어수선하고 인테리어도 친구 데리고 멀리서 예약하고 왔는데 많이 아쉬움이 남았습니다
사랑해요 빈티지 최고에요 빈티지 여기서 뇨끼먹으면 이제 더이상 다른 곳의 뇨끼를 먹을수없게되는 단점이 있음 버섯피자도 꼭 드세요
평일 저녁 시에 예약하고 갔습니다 가게마감은 시로 알고있었구요 근데 한 테이블정도 잇던 손님들이 다 드시고 저희만 남으니 더보기
맛있었어요 특히 빈티지 수제소스로 만든 피자가 계속 생각나요 뇨끼도 굿
음식 짜네요 분위기가 좋아서 별 한개 추가했어요 근데 비슷한 가격때에 그정도 분위기에 맛있는곳 이 더 많아서 가성비는 떨어지는 같아요
맛도 좋고 양도 많고 분위기도 좋습니다 추천합니다
네이버 평가가 하도 좋길래 가봤더니비싸고 맛없고 피자만 쏘하더구만 가격대비 가성비는 최악 블로그도 같은 음식사진 돌려쓰고돈주고 블로그 하는거 같음 속 더보기
월달을 맞아 오랜만에 판교에서 약속이 생겨서 전에 인상깊게 먹었던 곳이어서 찾아갔어요 인테리어도 바뀌었고 더 좋아진것 같아서 기대하고 음식을 먹어봤지만 맛이 더보기
최근 공사한 후에는 맛이 완전히 변했어요 뇨끼 무슨 감자떡인줄 이전으로 돌아가주세요
최근에 공사하느라 잠시 문을 닫았다 다시 열었는데 혹시 주방장이 바뀌었나요 간도 하나도 안맞는 음식들이라니 리조또며 피자며 다 예전 그 맛이 아니예요
음식 나오는 속도가 걸려요 뇨끼가 맛있어서 뇨끼 먹으러 또 오고싶네용
안심 크림 리조또 안심이 질김 자투리 고기로 해준거 같음 크림과 치즈가 어울리지 않아 느끼하기만 함 봉골레 조개가 오 더보기
안심리조또가 맛있어요 버섯 피자는 또 왜케 맛있는고야 자주 먹을 수 있게 가격 더보기
잠실점에서 갈아탄
깔꼼한 양식쓰
맛도 맛이지만 친절한 사장님이 인상깊다 가격대는 있는편 식기도 비싼 것만 있던
고르곤졸라에 함께나오는 무화과쨈 마싯더융
맛은 있는데 가격이 깡패라서 점
맛은 별다섯개
전반적으로 갠춘 판교치고는 굿
양이적고 맛은 약간 있지만 비싸다는 감이 크게 느껴짐
맛은 있는데 양도 적고 비싸요
두 분이 동업하시다 한분이 나가셨는데 그 때부터 실망스러운 맛을 보여줘서 안타까움 본래 괜찮은 집이었는데
맛있긴 한데 점심으로 자주 먹기엔 조금 비쌈
맛있고 친절하고 분위기 좋아요
무난했습니다 사시미는 양이 아쉽네요
아부리 사케동 맛있는데 양이 적어요 회사 식권 아니면 안 올 같아요 점심시간에 서둘러 안 오면 웨이팅 있어요
진짜 멀어도 매번 가는듯합니다 다 넘 맛있어요 최고 갈수록 더 맛있어지는듯한 기분탓인가암튼 사시미도 바지락들도 다 상태가 진짜 너무좋은것같아요
재방문의사 절대 없습니다 관자버터구이를 시켰으면 구이가 나와야지 왜 조림이 나오는거죠 그럼 메뉴판에 조림이라고 써놓는게 맞지않 더보기
사케동연어덮밥 퀄리티가 훌륭했어요 만족스러운 식사였습니다
사케동 맛있어요 배달로 먹어서 아쉬울 따름
이곳의 사케동은 우주 최강입니다
회사 근처 숨은 맛집 포장도 가능합니다
서비스가 좋고 맛있어요
친절하고 분위기는 좋지만 제가 가본 스타벅스 중 제일 맛이 별롭니다 시럽 파우더 류를 아껴서 싱겁습니다
다들 친절하십니다
이브닝아워 적용도 못하시는 두분은 교육이 필요해보입니다
회사에서 잠깐 나와 숨 돌리는 스벅
뭔가 이상한 쓱티커 붙어있는데 흠 스타벅스 돌려줘요 쓱타버스 말고
하나쯤 더생겨도 될듯
에이치스퀘어보다 덜 붐벼서 좋아용
하나로 부족했는데 하나 더 생겨서 좋아요
대방어 진심 맛있다 굴튀김도 추천
회가 하나도 안신선해요
일단 양이 나오는거 마다 적음 이 동네가 전체적으로 그럼 평균보다 비싸고 근데 조용히 데이트 하면서 술 마시기에는 괜찮음
테이블이 끈적하고 물티슈로 닦으면 검은 게 묻어 나와요 육회가 신선하지 않아서 도로 치워 달라고 했습니다 라면은 맛있어요
회를 주로 먹기에는 그렇다 양도 가격도
너무맛있어요 술이 술 들어갑니다 다음에 또올게요
방어회가 아주 좋음 가성비의 회주점
차로 가기좋음
근처에 회 파는곳이 많이 없어서 회 생각날때 가볍게 들르는 곳
회 자체는 신선하고 맛있어서 회만 추천 회 비싸지는 않으나 가격도 적은편 해물라면은 밍해서 더보기
쿠팡 이츠로 배달해서 먹었어요 광어회 소자와 매운탕거리 맛있었어요
왜 여기 좋은데 왜 평점이 이렇죠 점심 칼국수 존맛이요
해산물이 신선하고 좋아요
분위기 좋고 직원들이 손님 항상 의식 해산물 먹으러 가기 좋음
분당구 햄버거 맛집까지는 아닌거 같아요
진짜 맛집 평점 이상하네요 맛있는데 왜그러지
고구마 튀김이랑 어니언링은 꼭 드세요 별다섯개 그리고 무료 감자칩이랑 햄버거는 기름기를 쫙 더보기
파스 버거를 처음 접하는 것은 여의도점에서였다 그 맛이 좋아서 판교 점도 같은 체인점이니 똑같을 거라고 생각했다 그러나 결과는 실망이 크다 여의도점에서는 한 입 베어 물었을 때 패티에 따뜻한 온도가 햄버거 본연의 더보기
체인점이나 판교 버거 중 맛나게 먹고있습니다 바스버거의 장점은 갑자칩이 무료
햄버거 맛있고 감자칩도 맛있고 감자튀김도 맛있어요
치즈버거 바스버거 먹음 내입맛에는 맛있다고 평가됨 사람마다 취향은다르나 나는 브랜드 재방문의사 있 더보기
매장에서 먹을때 작은 바퀴벌레 기어다니는거보고 놀랬습니다 배달시킬때마다 식어오는것도 이상하구요
맛있다
예전에 알바했던 브랜드인데 오랜만에 시켜보니 진짜 왜 망해가는지 절로 이해됨 나 그만둘 때쯤부터 양상추 장씩 들어가던거 장 깔으라 그러고 버터 쓰던거 마가린으로 바뀌고 토마토 얇아지고 감튀양 줄이라고 등 지침 싹 바 더보기
맛있으나 알바는 바쁜척
예전에 왓을땐 버거킹이 더 낫었는데 지금은 존맛탱 시 라스트 오더
음식 빨리 나오고 맛있네용 고구마프라이가 맛있음 수제버거는 이 근방에서 이집이 젤 나은듯
장점 무료제공 감자칩은 맛있음 케챱과 마요네즈가 있다 페이코 사용 가능 단점 아 더보기
주문 받으시는 분 굉장히 불친절해요 오랜만에 바스버거 먹고싶어서 들뜬 마음으로 방문했는데 주문 받으시는 것부터 틱대는 말투로 포스기가 뚫어져라 더보기
맛은 있는데 알바생이 진짜 개싸갈스 바갈쓰 모자쓴 대 남자인데 볼펜으로 딱거리면서 주문받지를 않나일하기 시르면 하지마세요 그냥
바스버거 체인자체를 좋아해서 몇번 와본곳인데 딱히 친절은 못느껴본곳이긴함 무뚝뚝함 그리고 여기 영업시간 표시가 반영잘 안됨 닫아있었던 적이 꽤나 있음
여기 맛있어요 번창하세요
문 안열엇는데 왜 영업중이라고 뜨나요
수제햄버거
점심때 자리 잡기 힘든게 단점 햄버거 안좋아하는데 여기는 괜찮았음
대성했으면 좋겠어요 죽기전까지 먹게
무료 감자칩을 포함하면 가성비가 괜찮을까요 가격은 조금 나가지만 맛이나 서비스 등을 고려하면 괜찮은 곳이었네요
수제맥주 수제햄버거 감자튀김
버거는 육향이 많았지만 웨이팅해서 먹을 정도는 아니고 감튀가 짜고 오래된 느낌
햄버거보다 감자칩이 더 맛있어요
판교에서 제일 맛있었던 수제버거집 이젠 브루클린버거가 생겨서 잘 찾지 않게되었다
먹신 현주엽이 왔다갔다는 그렇게 맛있다는 빌리언박스에 친구하고 갔다왔습니다 버거가 작아서 많이 먹을줄 알고 개세트 개로 먹었는데 맛있었지만 치즈로 인해 느끼해서 개는 포장해왔습니다
배달시켜도 좋습니다
진짜 최악 감튀가 별로였음 기름이 많음 가격대비 더보기
맛이 변한듯 원래 버거치고 조금 가격대가 쎄도 제값하던 맛이었는데 참 아쉬움
안에들어가는 야채가 싱하고 빵이 엄청 촉하고 부드럽네요
뭔가 무겁지 않은 맛 소스가 덕지 주르륵 흐리지 않고 빵도 공기를 머금고 있는듯한 가벼움이 있어서 손으로 잘라 먹기도 용이함 서비스로 주는 감자칩도 은근 중독됨 가격대비는 부실한 느낌
맛있게 잘먹었습니다 하와이안버거 추천이요
무난
직원들 못들은 척하는것도 기술
블로그홍보조작뭔데
아 쫌 배달어플 포토리뷰처럼 달라고 뽑기운뭔데
치킨버거추천
동
버거는 무조건 바스버거 시킵니다 버거킹만 먹던 사람이었는데 근처에 바스버거있음 바로 주문 롯데리아나 맥날은 못먹는 입맛이 되어버림
맛은 있는데 가격대비 조금 아쉬워요 크기도 넘 작고 재방문 의사는 딱히
리뷰하신분들 맛있어 진심 더 놀라운건 세트시키면 인데 그 값어치를 하는지가 의문임
최고 맛집
맛나용
말해뭐해 법카로먹으면행복한메뉴
수제버거 맛집 단 지하라 그런지 기름냄세는 어쩔수 없을듯
치킨버거 존맛 감자튀김보다 그냥 주는 감자칩이 제 입에는 더 맛있네용
치킨버거 시나몬토스트쉐이크 조합 쉐이크 도장깨기 다해보고 드러눕겠음
특별히 맛없지는 않은데 수제버거라고 하기에는 아쉬운맛 굳이 판교에서 수제버거가 먹고싶으면 갈만하다 오히려 버거보다는 추가금을 내고 업그레이드 가능한 치즈베이컨프라이를 추천할만함
별로인거 같아요 오늘 재방문무료로 주시는 감자칩 신경써 주세요 지난번엔 사장님 친구 분이 손으로 집어먹고 오늘은 어린아이가 입으로 가져갔다가 다시 그자리에
맛은있는데 버거가 가격에 비해 째깐하다 맘스터치의 감튀랑 비슷한 버팔로 스틱으로 공짜로 변경 가능함
버거킹을 가겠다
근처 만삼천원 이상이면 배달 해줌 먹다보면 역시 햄버거는 패티맛이구나를 느낌 그래도 오픈한지 꽤 되었는데 일하시는분들의 효율성이 많이 떨어짐 점심시간에 오래걸림
가성비 갑 점심때 좀만 늦게가면 대기가 있긴 하지만 맛은 최고에요 늘 바스버거세트만 먹는데 다른것도 도전해보려고요
역시 햄버거는 맥주랑 먹어야돼 기본 바스버거에 내맘대로 추가하면 탐욕버거보다 더 탐욕 가득하게 더보기
적절한 가격에 적절한 힙함
맛있어용
바스버거가 가성비 좋음 머쉬룸 버거는 튀긴 버섯이 들어있는데 기대 이하 하지만 보통은 하니 판교에서 수제버거가 먹고싶다 싶으면 바스버거로
멀리 갈 필요 없이 판교 테크노밸리에서 제일 갈만한 수제버거집이랄까
알 랏킷 러빗
좋아욧
난 맛있게 먹었다 서비스로 다른 맛도 추가해주심
제 인생 가장 맛있는 젤라또고 일주일에 번씩 가던 사람인데요 앞으로 안가겠습니다 젊은 여자직원분 손님 대응 별로에요 매장손님 꼽주는 것도 더보기
사장님도 리뷰를 보시는지는 모르겠지만 여자 알바분 교육 다시 하셔야 할 같습니다 여기 젤라또 좋아해서 자주가는데 오늘 직원분 한명 더보기
맛은 있지만 가성비가 떨어집니다
아이스크림 부드럽고 맛있어요
근처 지난다면 들르고 싶은 곳 산뜻한 젤라또
눈물흘릴뻔했다해서 뽀또맛 먹어봤는데 진짜 맛있네요 짱
뽀또맛 먹고 눈물흘릴뻔함 맛있어서
점심 시간엔 사람이 많아 혼자 오래 자리에 있으면 눈치 보여요 한가지 맛만 시켰는데 서비스로 다른 맛 서비스로 약간 더 주심 베리굳
맛있당
주차도 편하고 맛있어서 좋아요
최애
투자하고 싶은 곳
엄청 친절하셔요 소르베류가 맛있었어요 쌀쩐내가 조금나고 초코는평범합니다
평점이 좋아서 많이 기대했는데 저는 걍 그랬습니다 꾸덕하지 않고 가벼운 맛이에요 진하지 않은 맛이랄까
내가 아이스할께 크림은 누가할래
맛 분위기 서비스 젤라또 맛집이지만 와플도 엄청 맛있음 항상 친절하시고 주말에 한산할때는 잠깐 들어가서 먹어도 기분좋음
최애 젤라또 맛집이에요
사장님이 엄청 친절하시고 환경을 사랑하고 보호하려는 마음이 잘 느껴져요 젤라또가 쫀득한 편은 아니지만 그 맛이 다양하고 재료의 신선함이 느껴지는 아이스크림집이에요 특히 밤맛 맛있어요 번창하세용
사장님 친절하고 재료 건강하고 가격 적당하고 더할 나위가 없다 더보기
과일맛 아이스크림 강추 특히 귤 집에서 아 이 과일은 이 맛이겠지 기대하며 냉동하면 걍 냉 더보기
포장용기를 직접 가져가면 굉장히 환영해주시는 곳이에요 모두 반찬통을 가지고 포장하러 갑쉬다 뽀또 제크를 같이 부숴주시는데 맛있음 더보기
별로예요
맛있다
최애맛집 맛도 다양하고 친절하심 매일 갈때마자 아이스크림 맛 종류들이 달라져있어서 즐거움 강추
종류에 따라 젤라또라기보단 소르베에 가깝긴 하지만 이정도 맛이면 인정해 줘야지 사장님 겁나 친절하심 그 많은 맛을 다 먹어보라함 현백 벤끼랑 더불어 판교 투톱
판교 테크노밸리에 위치한 젤라또 전문점 의외로 레드와인 아이스크림이 맛나고 전체적으로 괜찮네요 맛있게 먹었어요
최고
회사때문에 빡친 마음 여기서 다 가라앉음 여기 오는 사람 모두 같은 효과를 맛보시길
누룽지맛 존맛이에요 다음에도 또 가야지
꾸덕한 젤라또는 아니다 질감은 아주 가벼운 편 매일 메뉴가 바뀐다 백도 토마토 솔티크래커 찰옥수수 청포도 아직까지는 실패가 없다
피스타치오 코넛 맛있음 솔티크래커는 싫어할 사람 없을듯
진짜 맛있어요
우리집 여자 명 최애가게
솔티크래커너란 녀석 내 마음속에 저장할테야
분당의 보물 직접 제철 재료로 만드시는 아이스크림도 맛있지만 와플도 프레즐도 맛있어요
여긴 맛집 이태리유학파 장인의 걸작
맛도 다양하고 맛있음 특히 레드와인 녹차크림치즈 피스타치오 솔티크래커 토마토소르베가 진짜 존맛이었다
가성비최고 맛도 좋고 서비스도 푸짐 꼭 가보세요
젤라또 같진않고 가정에서 만드는 셔벗 같은 느낌 다른것 보다 가격이 인정사정 없음 가격만큼 고급진 더보기
가야는이유 이탈리아에서 인증받은 젤라띠에가 만드는 천연재료의 맛을 살리는 친절하신 안가는이유 판교에만 있는 일요일은 미리 연 더보기
맛은 있는데요 홈페이지엔 일요일도 영업하는 것처럼 되어있는데 실제로 와보니 문 닫았네요
젤라또가 맛있어요 직접 만드신 젤라또를 이것저것 맛보여주시는데 다 맛있어서 두개만 고르기가 힘들었습니다
와씨 핵맛
쏠티크래커만세
솔티크래커가 맛있었어요 맛이 궁금하다고 하면 맛보기로 조금씩 주심 친절하십니덩
친구가 추천해서 같이 가서 먹었는데 맛과 친절 좋았습니다 기본 안심과 등심 분위는 속은 부드럽고 겉은 바싹했습니다 그리고 베스트인 김치찜돈까스는 달콤시큼한 김치와 뚝배기 돈까스가 잘 어울렸습니다 김치 좋아하시는 더보기
예전에는 판교에 돈가스 맛집이라고 생각했는데 최근 두번은 다 실패네요 평범한 돈가스집이 되었습니 더보기
오픈런으로 웨이팅 안함 로스히레콤보와 로스카츠카레 먹음 히레도 더보기
진짜 맛있는데 가게 분들 다 친절하시고 멋지세요 아이있는 집도 편히 먹고갈수 있어요
남들이 뭐라해도 저의 마음에 등심 맛집입니다
돈까스 고기 퀼리티좋아요맛있습니다
돈가쓰 기본메뉴말고는 맛없음 김치찜돈가스인가 그냥 레토르트 전자렌지로 데워준것마냥맛없음
가끔씩 생각나는 김치찜돈까수
돈까스가 눅해요
맛있어요 다음엔 로스까스도 먹어볼게요
안심 굿
메뉴별 가격차이와 비례하지 않는 이상한 구성 서버들이 굉장히 불친절함 음식을 거의 던지듯이 서빙하는데 더보기
치즈가스 먹었는데 맛있었어요 그런데 치즈가 많아 돈까스 맛을 잘 못 느끼겠더라고요 다음에는 롯가스나 히레가스 먹어봐야겠어요
서호돈까스 새우나오는 걸로 드셈 튀김옷 얇 더보기
맛있어요
최근들어 더 맛있어졌어요 이 근처 돈까스 중 젤 괜찮아요
맛있음 웨이팅 있음
치즈돈가스는 내가 지금 피자를 먹고 있는지 치즈돈가스를 먹고 있는지 착각이 들었습니다 치즈돈가스 안에 양파 피망 버섯까지 들어가니 피자를 먹고 있는 같아서 제 입 더보기
등심 제주산 흑돈 밥 개맛있다
언제나 돈까스가땡길땐 여기로 갑니다 흰쌀밥도 맛난곳
웨이팅
새우튀김이 맛있어요
맛잇어요
고기가 좋아 돈까스 먹는 식감이 좋고 기름이 깨끗해서 그런지 튀김옷이 깔끔해요 돈까스 소스와 샐러드 소스는 특별할 거 없이 평이합니다 같이 더보기
너무맛있어용
매일 한정이라는 흑돼지특가츠를 못먹어서 아쉽 돈까스는 꽤 맛있다 튀김도 바삭한데 고기 자체 질이 좋아보였고 한돈인증점 마크도 붙어있다
돈가스도 두툼바삭하니 맛있고 김치우동도 맛있어요
고기 엄청 부드러움 야채소스 짱맛 포장가능합니다
흑돼지 돈가스 치즈돈가스 맛있었어요
맛나요
방문할때마다 맛이 변하는 거 같음 맛에 비해 가격이 아쉽 판교가 다 그렇지 뭐
생선가스 맛집 모밀은 오래 걸릴 수 있으니 주의 한때 판교 최애 맛집이었으나
야근저녁
맛이 나쁘진 않은데 사진에서 보듯이 기름이 뚝 떨어질 정도로 많이 기름지고 느끼하다 요즘 스타일이 아닌 옛날 스타일의 돈가스
돈까스 포장해다 먹었는데 아주 괜찮았음
맛도 괜찮고 메뉴 구성도 좋은 편입니다
주변에 이 정도 집이 없어서
나베는 쏘 다음엔 다른거 도전
돈까스는 기름에 쩔어있어서 거시기함 냉모밀은 나름 먹을만하다
명인정식 만원
돈가스 땡기는 날 가볼만 해요
판교에서 제일 괜찮은 돈까스집이라고 생각 친절하고 맛도 좋다 분위기도 조용함
판교에서 보기드문 나름 소울 있는 일본식 돈까스집 돈까스 모밀 등 다 나름 괜춘 깔끔하고 테이블도 꽤 있는데 점심에는 웨이팅이 꽤 길수 있음
소바 먹고싶을 땐 무조건 여기
판교로 옮겨진 하루 가격은 다소 있지만 만족도는 항상 최고
맛 있고 분위기 좋고 친절하시고 좋았습니다
튀김이 아주 맛있었습니다 음식들이 간이 세지 않아 좋았어요 튀김도 바로 튀겨서 가져다 주셔서 맛있게 잘먹었네요 다만 가성비를 생각하면 흠
판교에이치스퀘어 에스동에 새로 오픈한 일식당 하루 인테리어 바깥 풍경 예쁘고 동백에서 유명한 일식당이 판교로 이전했네요 소바 단품하고 튀김 더보기
룸술집이라 명 얘기하기 좋아요
가격은 있지만 룸이 있어서 회식하기엔 좋아요
에비동 맛있어요 새우가 오동통통해서 좋아요 근데 정식이라 양이 많아서 단품이랑 정식 중에 택할 수 있으면 좋겠어요
점심때 예약방문하였고 초밥정식은 분 이상 걸린다고해서 일행들 다 덮밥시킴 근데 옆 테이블 초밥정식 먼저 나오고 심지어 다 먹고 나갈동안 우리팀 음식 시간이 지나서도 안나왔음 장사할 생각 있는거 맞죠
다소 비싼데 분위기는 괜찮다 우동이랑 계란찜은 사이드지만 완전 소울리스
맛과 가격은 별로지만 다미룸이 좋음
안주는 다 괜찮았어요
회사 근처 맛집 김치나베돈까스 존맛
회사근처맛집
예전에구 이태원 천상 문제가 있었는데 오늘 먹어본바로는 꽤 괜찮았어요 초밥을 직접 만들어먹는것도 괜찮았어요 제가 먹고싶은 만큼의 밥양을 조절할수 있어서
양꼬치 꿔바로우 맛있었어요
양꼬치 전체적으로 괜찮았습니다
맛있어요 옆가게 같은 사장님이라 족발도 시켜먹을수 있어요
자리가 비교적 넓고 깔끔해서 좋다
깔끔
회식으로 판교에 있는 스시쿤을 방문하였다 가격도 인당 여만원 정도로 적당했다 판교역에서 다소 거리가 있는 편이라 걸어서 분 정도 걸렸다 유스페이스에 있어서 그 근처 회사 회식으로는 알맞지 않나 싶다 생각보다 크지는 않았고 평일 저녁임에도 다른 손님들이 없어서 우리끼리 편안하게 먹을 수 있었다 처음에는 간단한 회가 나왔고 이어서 전복

In [59]:
df.head()

,ID,상호명,주소,메뉴,리뷰,일,월,화,수,목,금,토,평균별점,위도,경도,대표_카테고리,메인_메뉴_형태,url,리뷰_평균임베딩,메뉴_임베딩
0,1,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골,https://place.map.kakao.com/27582913,"[-0.8459975123405457, -0.050718024373054504, -...",None
1,2,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호","['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이,https://place.map.kakao.com/269932132,"[-0.9467869400978088, 0.16819141805171967, -0....",None
2,3,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,"['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,10:40~21:00,10:40~21:00,4.083333,37.402068,127.106671,한식,삼계탕,https://place.map.kakao.com/18561415,"[-0.9609801769256592, -0.015692124143242836, -...",None
3,4,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN,https://place.map.kakao.com/409216346,"[-1.2563763856887817, 0.07891209423542023, -0....",None
4,5,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,"['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,11:30~22:00,15:00~21:30,4.153846,37.400694,127.106989,한식,고기구이,https://place.map.kakao.com/1782830414,"[-1.1126253604888916, -0.07402823120355606, -0...",None

In [61]:
from sentence_transformers import SentenceTransformer
import ast

# SBERT 모델 로드
model = SentenceTransformer('snunlp/KR-SBERT-V40K-klueNLI-augSTS')

# 메뉴 임베딩 함수
def embed_menu(row):
    category = row['대표_카테고리']  # 한식, 일식 등

    # 메인_메뉴 우선
    try:
        main_menu = ast.literal_eval(row['메인_메뉴_형태']) if not pd.isna(row['메인_메뉴_형태']) else []
    except:
        main_menu = []

    # 메인_메뉴 없으면 메뉴 전체를 사용
    if not main_menu:
        try:
            full_menu = ast.literal_eval(row['메뉴']) if not pd.isna(row['메뉴']) else []
        except:
            full_menu = []
        menu_list = full_menu
    else:
        menu_list = main_menu

    if not category or not menu_list:
        return None

    # 자연어 프롬프트 생성
    prompt = f"이 식당은 {category} 전문점입니다. 주요 메뉴로는 {', '.join(menu_list)}가 있습니다. 이 식당의 음식 스타일을 임베딩하세요."

    # SBERT 임베딩
    return model.encode(prompt).tolist()

# 적용
df['메뉴_임베딩'] = df.apply(embed_menu, axis=1)

In [62]:
df.head()

,ID,상호명,주소,메뉴,리뷰,일,월,화,수,목,금,토,평균별점,위도,경도,대표_카테고리,메인_메뉴_형태,url,리뷰_평균임베딩,메뉴_임베딩
0,1,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골,https://place.map.kakao.com/27582913,"[-0.8459975123405457, -0.050718024373054504, -...","[-0.4842810332775116, -0.2825833559036255, 0.6..."
1,2,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호","['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이,https://place.map.kakao.com/269932132,"[-0.9467869400978088, 0.16819141805171967, -0....","[-0.3743784427642822, -0.14427725970745087, 0...."
2,3,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,"['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,10:40~21:00,10:40~21:00,4.083333,37.402068,127.106671,한식,삼계탕,https://place.map.kakao.com/18561415,"[-0.9609801769256592, -0.015692124143242836, -...","[-0.60927814245224, -0.21875445544719696, 0.55..."
3,4,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN,https://place.map.kakao.com/409216346,"[-1.2563763856887817, 0.07891209423542023, -0....","[-0.2550734281539917, -0.2999421954154968, -0...."
4,5,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,"['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,11:30~22:00,15:00~21:30,4.153846,37.400694,127.106989,한식,고기구이,https://place.map.kakao.com/1782830414,"[-1.1126253604888916, -0.07402823120355606, -0...","[-1.0606603622436523, -0.09205537289381027, 0...."

In [63]:
df.to_csv('임베딩_완료.csv', index=False)

In [14]:
df = pd.read_csv('/Users/kimss/Documents/marong/임베딩_완료.csv')
df

,ID,상호명,주소,메뉴,리뷰,일,월,화,수,목,금,토,평균별점,위도,경도,대표_카테고리,메인_메뉴_형태,url,리뷰_평균임베딩,메뉴_임베딩
0,1,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골,https://place.map.kakao.com/27582913,"[-0.8459975123405457, -0.050718024373054504, -...","[-0.4842810332775116, -0.2825833559036255, 0.6..."
1,2,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호","['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이,https://place.map.kakao.com/269932132,"[-0.9467869400978088, 0.16819141805171967, -0....","[-0.3743784427642822, -0.14427725970745087, 0...."
2,3,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,"['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,10:40~21:00,10:40~21:00,4.083333,37.402068,127.106671,한식,삼계탕,https://place.map.kakao.com/18561415,"[-0.9609801769256592, -0.015692124143242836, -...","[-0.60927814245224, -0.21875445544719696, 0.55..."
3,4,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN,https://place.map.kakao.com/409216346,"[-1.2563763856887817, 0.07891209423542023, -0....","[-0.2550734281539917, -0.2999421954154968, -0...."
4,5,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,"['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,11:30~22:00,15:00~21:30,4.153846,37.400694,127.106989,한식,고기구이,https://place.map.kakao.com/1782830414,"[-1.1126253604888916, -0.07402823120355606, -0...","[-1.0606603622436523, -0.09205537289381027, 0...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,693,메가MGC커피 판교백현화랑초점,경기 성남시 분당구 동판교로 92 백현마을3단지 상가동 1층 104호,"['하츄핑 딸기 밀크쉐이크', '치즈가 펑펑 눈꽃 떡볶이', '빤짝핑 망고 밀크쉐이...","{'리뷰 1': {'별점': 1, '리뷰 내용': '10시 30분까지라고 되어있어서...",08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,08:00~22:30,1.000000,37.391749,127.118148,카페/디저트,NaN,https://place.map.kakao.com/107494195,"[-1.3729053735733032, -0.07564281672239304, -0...","[-1.144076943397522, -1.1582812070846558, -0.5..."
693,694,카페만월경 판교백현점,경기 성남시 분당구 판교역로 102 백현마을5단지아파트 나상가동 1층 104호,"['연한아메리카노', '진한아메리카노', '카페라떼', '카페모카', '바닐라라떼'...","{'리뷰 1': {'별점': 3, '리뷰 내용': '음료가 너무 달아요... 혀 마...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,37.390951,127.112714,카페/디저트,NaN,https://place.map.kakao.com/289860524,"[-1.2606201171875, 0.11040152609348297, -0.785...","[-1.347531795501709, -0.7940172553062439, -0.0..."
694,695,커스텀커피 서판교점,경기 성남시 분당구 운중로125번길 6 1층 101호,"['아메리카노', '카페라떼', '바닐라라떼', '아이스티', '청포도에이드']","{'리뷰 1': {'별점': 5, '리뷰 내용': '라떼는 여기만 가요!', '날짜...",08:00~19:00,08:00~19:00,08:00~19:00,08:00~19:00,NaN,10:00~19:00,10:00~19:00,4.333333,37.392302,127.077418,카페/디저트,NaN,https://place.map.kakao.com/554540956,"[-0.9191390872001648, -0.2648675739765167, -0....","[-1.3143316507339478, -0.8328792452812195, 0.4..."
695,696,BK버거 판교점,경기 성남시 분당구 판교역로 136 1층 1036호,"['BK 오리지날버거 세트', 'BK 리얼치즈버거 세트', 'BK 더블리얼치즈버거 ...","{'리뷰 1': {'별점': 4, '리뷰 내용': '더블치즈 먹었는데 맛있네요 ! ...",11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,11:00~21:00,4.285714,37.392084,127.109167,패스트푸드,햄버거,https://place.map.kakao.com/1737054932,"[-1.1283447742462158, -0.05111432075500488, -0...","[-0.36813217401504517, -0.601417064666748, -0...."
696,697,판교도마집 판교본점,경기 성남시 분당구 판교역로192번길 14-1 1층,"['육즙목살', '꼬들목살', '등심덧살', '쫀득살', '치마살', '된장술밥',...","{'리뷰 1': {'별점': 1, '리뷰 내용': '일하는 여자분 최악입니다\n아 ...",16:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,18:00~24:00,16:00~24:00,3.222222,37.397511,127.111804,한식,고기구이,https://place.map.kakao.com/362906944,"[-0.845283031463623, -0.015390897169709206, -0...","[-0.5711670517921448, -0.24651558697223663, 0...."

In [15]:

# 임베딩 컬럼 파싱 (문자열을 리스트로)
def parse_embedding(emb_str):
    try:
        emb = ast.literal_eval(emb_str)
        return emb
    except:
        return None

df['리뷰_평균임베딩'] = df['리뷰_평균임베딩'].apply(parse_embedding)
df['메뉴_임베딩'] = df['메뉴_임베딩'].apply(parse_embedding)

# 둘 다 있는 경우만 남기기
df = df[df['리뷰_평균임베딩'].notna() & df['메뉴_임베딩'].notna()]
df.head()

,ID,상호명,주소,메뉴,리뷰,일,월,화,수,목,금,토,평균별점,위도,경도,대표_카테고리,메인_메뉴_형태,url,리뷰_평균임베딩,메뉴_임베딩
0,1,평가옥 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호,"['평양물냉면', '평양비빔냉면', '접시만두 (6개)', '편육 (소)', '명품...","{'리뷰 1': {'별점': 4, '리뷰 내용': '평냉 초보로서 입문용으로 적극 ...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.215686,37.401234,127.107518,한식,만두전골,https://place.map.kakao.com/27582913,"[-0.8459975123405457, -0.050718024373054504, -...","[-0.4842810332775116, -0.2825833559036255, 0.6..."
1,2,봉피양 판교점,"경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 121,122호","['돼지목심木갈비', '석쇠양념구이', '한우양곰탕', '한우도가니탕', '한우뚝배...","{'리뷰 1': {'별점': 4, '리뷰 내용': '비싸깅한데 맛은 있어요', '날...",11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,11:00~21:30,3.358209,37.401795,127.109666,한식,고기구이,https://place.map.kakao.com/269932132,"[-0.9467869400978088, 0.16819141805171967, -0....","[-0.3743784427642822, -0.14427725970745087, 0...."
2,3,토속상황삼계탕,경기 성남시 분당구 대왕판교로 670 유스페이스2 2층 225호,"['상황삼계탕 (1인분)', '들깨삼계탕 (1인분)', '한방삼계탕 (1인분)', ...","{'리뷰 1': {'별점': 5, '리뷰 내용': '리뷰 없음', '날짜': '20...",10:40~21:00,10:40~21:00,10:40~21:00,NaN,NaN,10:40~21:00,10:40~21:00,4.083333,37.402068,127.106671,한식,삼계탕,https://place.map.kakao.com/18561415,"[-0.9609801769256592, -0.015692124143242836, -...","[-0.60927814245224, -0.21875445544719696, 0.55..."
3,4,팔복판교,경기 성남시 분당구 판교역로241번길 22 판교엠타워 1층,"['오향장육(안휘성)', '팔복 특품 양장피 (소)', '마라튜린지(소)', '목화...","{'리뷰 1': {'별점': 5, '리뷰 내용': '내 사랑 라즈지 최고 맛집. 라...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,4.272727,37.402724,127.106795,중식,NaN,https://place.map.kakao.com/409216346,"[-1.2563763856887817, 0.07891209423542023, -0....","[-0.2550734281539917, -0.2999421954154968, -0...."
4,5,화포식당 판교점,경기 성남시 분당구 대왕판교로 660 유스페이스1 2층 240호,"['명품 한우 꽃등심', '명품 한우 차돌', '명품 한우 육회', '명품 숙성 오...","{'리뷰 1': {'별점': 5, '리뷰 내용': '고기가 맛있고 질도 너무 좋아요...",11:30~22:00,11:30~22:00,11:30~22:00,11:30~22:00,NaN,11:30~22:00,15:00~21:30,4.153846,37.400694,127.106989,한식,고기구이,https://place.map.kakao.com/1782830414,"[-1.1126253604888916, -0.07402823120355606, -0...","[-1.0606603622436523, -0.09205537289381027, 0...."

In [ ]:
import pandas as pd
import numpy as np
import ast
import chromadb
from chromadb.config import Settings

# ✅ ChromaDB 로컬 연결
chroma_client = chromadb.PersistentClient(
    path="./chroma_db",   # 저장할 경로
    settings=Settings(anonymized_telemetry=False)
)

# ✅ 데이터 불러오기
df = pd.read_csv('/Users/kimss/Documents/marong/임베딩_완료.csv')

# ✅ 벡터 파싱 함수
def parse_embedding(emb_str):
    try:
        emb = ast.literal_eval(emb_str)
        return np.array(emb)
    except:
        return None

df['리뷰_평균임베딩'] = df['리뷰_평균임베딩'].apply(parse_embedding)
df['메뉴_임베딩'] = df['메뉴_임베딩'].apply(parse_embedding)

# ✅ 컬렉션 2개 생성
collection_reviews = chroma_client.get_or_create_collection(
    name="review_embeddings",
    embedding_function=None
)

collection_menus = chroma_client.get_or_create_collection(
    name="menu_embeddings",
    embedding_function=None
)

# ✅ 데이터 업로드
for idx, row in df.iterrows():
    store_id = f"store_{idx}"

    # 공통 metadata (영업시간 포함)
    base_metadata = {
        "상호명": row.get('상호명', ''),
        "대표메뉴": row.get('대표_카테고리', ''),
        "메인_메뉴": row.get('메인_메뉴_형태', ''),
        "주소": row.get('주소', ''),
        "URL": row.get('URL', ''),
        "평균별점": row.get('평균별점', ''),
        "월": row.get('월', ''),
        "화": row.get('화', ''),
        "수": row.get('수', ''),
        "목": row.get('목', ''),
        "금": row.get('금', ''),
        "토": row.get('토', ''),
        "일": row.get('일', ''),
        "위도": row.get('위도', ''),
        "경도": row.get('경도', ''),
    }

    # 리뷰_평균임베딩 저장
    if row['리뷰_평균임베딩'] is not None:
        collection_reviews.add(
            documents=[row.get('상호명', '')],
            embeddings=[row['리뷰_평균임베딩'].tolist()],
            metadatas=[base_metadata],
            ids=[store_id]
        )

    # 메뉴_임베딩 저장
    if row['메뉴_임베딩'] is not None:
        collection_menus.add(
            documents=[row.get('상호명', '')],
            embeddings=[row['메뉴_임베딩'].tolist()],
            metadatas=[base_metadata],
            ids=[store_id]
        )

print("✅ 모든 데이터 업로드 완료")
print(f"리뷰 컬렉션 문서 수: {collection_reviews.count()}")
print(f"메뉴 컬렉션 문서 수: {collection_menus.count()}")

InternalError: Query error: Database error: error returned from database: (code: 1032) attempt to write a readonly database

In [1]:
import pandas as pd
import numpy as np
import ast
import chromadb
from chromadb.config import Settings
import torch.nn.functional as F
import torch

# ✅ 정규화 함수 추가
def normalize_vector(vec):
    return F.normalize(torch.tensor(vec, dtype=torch.float32), dim=0).tolist()


# ✅ ChromaDB 로컬 연결
chroma_client = chromadb.PersistentClient(
    path="./chroma_db",  # 로컬 폴더
    settings=Settings(anonymized_telemetry=False)
)

# ✅ 두 개 컬렉션 생성
review_collection = chroma_client.get_or_create_collection(name="review_collection")
menu_collection = chroma_client.get_or_create_collection(name="menu_collection")

# ✅ 데이터 불러오기
df = pd.read_csv('/Users/kimss/Documents/marong/임베딩_완료.csv')

# ✅ 벡터 파싱 함수
def parse_embedding(emb_str):
    try:
        emb = ast.literal_eval(emb_str)
        return np.array(emb)
    except:
        return None

# ✅ 컬럼 파싱
df['리뷰_평균임베딩'] = df['리뷰_평균임베딩'].apply(parse_embedding)
df['메뉴_임베딩'] = df['메뉴_임베딩'].apply(parse_embedding)

# ✅ 유효 데이터 필터링
valid_documents = []
valid_review_embs = []
valid_menu_embs = []
valid_metadatas = []
valid_ids = []

for idx, row in df.iterrows():
    review_emb = row['리뷰_평균임베딩']
    menu_emb = row['메뉴_임베딩']

    if review_emb is not None and menu_emb is not None:
        valid_documents.append(row['상호명'])
        valid_review_embs.append(normalize_vector(review_emb))
        valid_menu_embs.append(normalize_vector(menu_emb))

        metadata = {
            "상호명": row.get('상호명', ''),
            "대표카테고리": row.get('대표_카테고리', ''),
            "메인_메뉴": row.get('메인_메뉴_형태', ''),
            "주소": row.get('주소', ''),
            "평균별점": row.get('평균별점', ''),
            "영업시간": row.get('영업시간_요약', ''),
            "위도": row.get('위도', ''),
            "경도": row.get('경도', ''),
            "링크": row.get('링크', '')
        }
        valid_metadatas.append(metadata)
        valid_ids.append(f"store_{idx}")

# ✅ 배치 업로드 함수
def add_to_chroma_in_batches(collection, documents, embeddings, metadatas, ids, batch_size=500):
    for i in range(0, len(documents), batch_size):
        batch_docs = documents[i:i+batch_size]
        batch_embs = embeddings[i:i+batch_size]
        batch_meta = metadatas[i:i+batch_size]
        batch_ids = ids[i:i+batch_size]

        collection.add(
            documents=batch_docs,
            embeddings=batch_embs,
            metadatas=batch_meta,
            ids=batch_ids
        )
        print(f"✅ Added batch {i // batch_size + 1}")

# ✅ 업로드 실행
add_to_chroma_in_batches(review_collection, valid_documents, valid_review_embs, valid_metadatas, valid_ids)
add_to_chroma_in_batches(menu_collection, valid_documents, valid_menu_embs, valid_metadatas, valid_ids)

# ✅ 문서 수 확인
print("리뷰 컬렉션 문서 수:", review_collection.count())
print("메뉴 컬렉션 문서 수:", menu_collection.count())

✅ Added batch 1
✅ Added batch 2
✅ Added batch 1
✅ Added batch 2
리뷰 컬렉션 문서 수: 607
메뉴 컬렉션 문서 수: 607

In [7]:
import os
import chromadb
from chromadb.config import Settings

# ✅ 디렉토리 경로
CHROMA_DB_PATH = "./chroma_db"

# ✅ 디렉토리가 없으면 자동 생성
os.makedirs(CHROMA_DB_PATH, exist_ok=True)

# ✅ ChromaDB 연결
chroma_client = chromadb.PersistentClient(
    path=CHROMA_DB_PATH,
    settings=Settings(anonymized_telemetry=False)
)

In [ ]:
from chromadb import PersistentClient
from sentence_transformers import SentenceTransformer
from recommend_place import RecommendPlace
from mbti_projector import MBTIProjector  # 너가 만든 모델 모듈
import torch


embedding_model = SentenceTransformer("snunlp/KR-SBERT-V40K-klueNLI-augSTS")
mbti_model = MBTIProjector()
mbti_model.load_state_dict(torch.load("best_mbti_projector.pt", map_location="cpu"))
mbti_model.eval()

chroma_client = PersistentClient(path="/Users/kimss/Documents/marong/chroma_db")

# 아래 줄이 반드시 실행돼야 init 내부 print들이 보임
recommender = RecommendPlace(
    model=mbti_model,
    embedding_model=embedding_model,
    mbti_vector=[0.5, 0.5, 0.5, 0.5],
    chroma_client=chroma_client,
    review_col_name="review_collection",
    menu_col_name="menu_collection",
    allow_cafe=True
)

results = recommender.recommend(
    lat=37.394726159,
    lng=127.111209047,
    radius_km=15.0,
    like_foods=["고기", "된장찌개"],
    dislike_foods=["라멘"]
)

print("리뷰 컬렉션 수:", recommender.review_collection.count())
print("메뉴 컬렉션 수:", recommender.menu_collection.count())
for r in results:
    print(r)

📌 RecommendPlace 초기화 시작
✅ 모델 구조: MBTIProjector(
  (net): Sequential(
    (0): Linear(in_features=768, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=768, bias=True)
  )
)
✅ 디바이스: cpu
✅ 컬렉션 불러오기 완료
✅ 추출된 MBTI 키워드: ['외향적이고 활발한/내성적이고 조용한 균형', '감각적이고 경험을 중시하는/직관적이고 상상력이 풍부한 균형', '논리적이고 사고를 중시하는/감성적이고 공감력이 좋은 균형', '계획적이고 절차를 중시하는/즉흥적이고 유연한 균형']
✅ 키워드 임베딩 완료. 개수: 4
✅ 평균 벡터 shape: torch.Size([1, 768])
✅ 사용자 벡터 생성 완료. shape: (1, 768)

📌 추천 시작
👍 좋아하는 음식: 고기
👍 좋아하는 음식: 된장찌개
👎 싫어하는 음식: 라멘
✅ 최종 사용자 벡터 shape: (1, 768)
🔍 리뷰 컬렉션에서 유사도 검색 중...
✅ 리뷰 검색 결과 개수: 100
🔍 메뉴 컬렉션에서 유사도 검색 중...
✅ 메뉴 검색 결과 개수: 100

🏁 최종 추천 개수: 1
리뷰 컬렉션 수: 607
메뉴 컬렉션 수: 607
{'name': '파머스마켓팥집', 'address': '경기 성남시 분당구 판교로25번길 18-3 1층 102호', 'rating': 4.71428571428571, 'distance': 2.5270770376353866, 'link': 'https://place.map.kakao.com/1601052029', 'score': 0.09561825546610397}

In [ ]:
from chromadb import PersistentClient
from sentence_transformers import SentenceTransformer
from recommend_place import RecommendPlace
from mbti_projector import MBTIProjector  # 너가 만든 모델 모듈
import torch


embedding_model = SentenceTransformer("snunlp/KR-SBERT-V40K-klueNLI-augSTS")
mbti_model = MBTIProjector()
mbti_model.load_state_dict(torch.load("best_mbti_projector.pt", map_location="cpu"))
mbti_model.eval()

chroma_client = PersistentClient(path="/Users/kimss/Documents/marong/chroma_db")

# 아래 줄이 반드시 실행돼야 init 내부 print들이 보임
recommender = RecommendPlace(
    model=mbti_model,
    embedding_model=embedding_model,
    mbti_vector=[0.5, 0.5, 0.5, 0.5],
    chroma_client=chroma_client,
    review_col_name="review_collection",
    menu_col_name="menu_collection",
    allow_cafe=True
)

results = recommender.recommend(
    lat=37.394726159,
    lng=127.111209047,
    radius_km=7.0,
    like_foods=["라멘"],
    dislike_foods=["고기"]
)

print("리뷰 컬렉션 수:", recommender.review_collection.count())
print("메뉴 컬렉션 수:", recommender.menu_collection.count())
for r in results:
    print(r)

최종 추천 개수: 5
리뷰 컬렉션 수: 607
메뉴 컬렉션 수: 607
{'name': '트러스트스페셜티커피 판교점', 'address': '경기 성남시 분당구 판교역로 235', 'rating': 5.0, 'distance': 0.8469997220667699, 'link': 'https://place.map.kakao.com/1543518479', 'score': 0.5075667297268233}
{'name': '커스텀커피 삼평동점', 'address': '경기 성남시 분당구 대왕판교로 670 1층', 'rating': 5.0, 'distance': 0.9095131575001097, 'link': 'https://place.map.kakao.com/1666811050', 'score': 0.4935618655216149}
{'name': '하품스베이크 판교점', 'address': '경기 성남시 분당구 판교역로 235', 'rating': 5.0, 'distance': 0.8469997220667699, 'link': 'https://place.map.kakao.com/1276139149', 'score': 0.49194360131266923}
{'name': '마키아티 판교점', 'address': '경기 성남시 분당구 대왕판교로 660 유스페이스1 A동 1층 129호', 'rating': 5.0, 'distance': 0.06639226081065448, 'link': 'https://place.map.kakao.com/1313606369', 'score': 0.4855163336642759}
{'name': '코멧츠', 'address': '경기 성남시 분당구 판교역로 235 H스퀘어 N동 1층 107호', 'rating': 5.0, 'distance': 0.7978054614669056, 'link': 'https://place.map.kakao.com/448410287', 'score': 0.4784809285751157}

In [ ]:
import recommend_place
print(recommend_place.__file__)

/Users/kimss/Documents/marong/RecommendPlace.py

In [ ]:
import pandas as pd
import numpy as np
import chromadb
from chromadb.config import Settings

# ✅ ChromaDB 연결
client = chromadb.PersistentClient(path="/Users/kimss/Documents/marong/chroma_db")  # 너가 지정한 경로

# ✅ 컬렉션 로딩
menu_col = client.get_collection("menu_collection")
review_col = client.get_collection("review_collection")

# ✅ 모든 document 가져오기
menu_docs = menu_col.get(include=["metadatas"])
review_docs = review_col.get(include=["metadatas"])

# ✅ 각 document의 metadata 추출
menu_df = pd.DataFrame(menu_docs["metadatas"])
review_df = pd.DataFrame(review_docs["metadatas"])

# ✅ place_id 기준 merge
merged_df = pd.merge(menu_df, review_df, on="링크", suffixes=("_menu", "_review"))

# ✅ 필요한 컬럼 정제
df = merged_df[["상호명_menu", "평균별점_menu", "링크", "경도_menu", "위도_menu"]].copy()

# ✅ 거리 역수 처리 (가까울수록 좋은 특성으로 만들기)
df["distance"] = 1 / df["distance"]

# ✅ 정규화 및 엔트로피 가중치 계산
def calculate_entropy_weights(df):
    norm_df = df / df.sum()
    k = 1 / np.log(len(df))
    entropy = -k * (norm_df * np.log(norm_df + 1e-12)).sum()
    diversity = 1 - entropy
    weights = diversity / diversity.sum()
    return weights

# ✅ 엔트로피 기반 가중치 계산
feature_df = df[["menu_similarity", "review_similarity", "rating", "distance"]]
weights = calculate_entropy_weights(feature_df)

# ✅ 출력
print("🚀 엔트로피 기반 가중치 결과:")
for col, w in weights.items():
    print(f"{col} 가중치: {w:.4f}")

KeyError: 'place_id'

In [2]:
print(menu_docs["metadatas"][0])
print(review_docs["metadatas"][0])

{'월': '11:00~21:30', '수': '11:00~21:30', '링크': 'https://place.map.kakao.com/27582913', '경도': 127.1075184, '화': '11:00~21:30', '상호명': '평가옥 판교점', '평균별점': 3.2156862745098, '목': '11:00~21:30', '주소': '경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호', '일': '11:00~21:30', '위도': 37.4012343, '대표카테고리': '한식', '메인_메뉴': '만두전골', '금': '11:00~21:30', '토': '11:00~21:30'}
{'메인_메뉴': '만두전골', '목': '11:00~21:30', '토': '11:00~21:30', '경도': 127.1075184, '링크': 'https://place.map.kakao.com/27582913', '화': '11:00~21:30', '위도': 37.4012343, '금': '11:00~21:30', '대표카테고리': '한식', '평균별점': 3.2156862745098, '일': '11:00~21:30', '상호명': '평가옥 판교점', '수': '11:00~21:30', '월': '11:00~21:30', '주소': '경기 성남시 분당구 대왕판교로 660 유스페이스몰1 A동 102호'}